name: "Deploy new pages build"

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: pages  # Checkout the 'pages' branch if it exists
          fetch-depth: 0  # Get full branch history
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
           if ( -f package-lock.json ); then
             npm ci
           else
             npm install
           fi
      - run: npm run build

      - name: Deploy to Pages Branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Ensure we are on the 'pages' branch, or create it if missing
          git checkout pages || git checkout -b pages
          
          # Copy new build to the root of the branch
          cp -r .app/* ./
          
          # Stage, commit, and push changes
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Deploy updated build to pages branch"
          git push origin pages
